### PR TITLE
Vagrantfiles with xDebug

### PR DESCRIPTION
**Pull request by jan-secalith**
- fixed doctrine migrations
- configured xDebug with idekey "PHPSTORM"

### CODE REVIEW

**Comment by olegkrivtsov** [comment]
Hi @jan-secalith thanks for your PR! I'm not a specialist in Vagrant, so my questions:
 * I see that you use some custom APT repository here. Is that necessary? 
 * What about CentOS/Yum? Will CentOS users be able to use this file? 
 * Also, I see that you use PHPStorm IDE, but in this book I describe how to use NetBeans, so will Netbeans users be able to install this?

**Comment by jan-secalith** [comment]
Hi @olegkrivtsov 
I am not sure what do you mean by the custom apt repository. Is it about php-xdebug? I have installed xdebug as part of development stack, which the Vagrant (i guess) supposed to bring up.
The initial Vagrantfile was configured for ubuntu so what I just did was to expand the given OS. I have not tested it with centOs yet.
Used phpstorm idekey as I believe that is used by the minority of devs. I will change the default idekey to netbeans then.

**Comment by jan-secalith** [comment]
HI Oleg,
The original Vagrant boxes use ubuntu-14 (trusty).
The custom apt repo which you mentioned, I am guessing it was about `add-apt-repository ppa:ondrej/php` that was the popular way of installing newest PHP, the repository was there when I picked up the Vagrantfiles.

I would be more than happy to update the Vagrantfiles so it would use Ubuntu-18, but that is separate issue from what I am committing. 

As of Centos, I think that would need to build separate Vagrantfiles just for Centos.

I am having an idea of building two types for the repository. One centos and one ubuntu, but i am not sure how would that be managed smoothly in terms of branching. separate branch for centos and separate for ubuntu? not sure if that would be efficient.

**Comment by olegkrivtsov** [comment]
Hi @jan-secalith hmm.. can't advice about CentOS, let's just keep the simplified version for now.

**Comment by olegkrivtsov** [comment]
Thanks @jan-secalith, merged.

**Pull request merged**
